[project]
name = "self-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.72.0",
    "httpx>=0.28.1",
    "mcp[cli]>=1.20.0",
    "python-dotenv>=1.2.1",
]
